source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

def shared_pods
  pod "PhotoSlider", :path => "../"
  pod 'SDWebImage'
end

target 'PhotoSliderDemo', :exclusive => true do
  shared_pods
end

target 'PhotoSliderDemoTests', :exclusive => true do
  shared_pods
end

target 'PhotoSliderDemoUITests', :exclusive => true do
  shared_pods
end
