source 'https://github.com/CocoaPods/Specs.git'

platform :ios, "8.0"
use_frameworks!

target 'PhotoSliderDemo', :exclusive => true do
  pod "PhotoSlider", :path => "../"
  pod 'SDWebImage'
end

target 'PhotoSliderDemoTests', :exclusive => true do
  pod "PhotoSlider", :path => "../"
  pod 'SDWebImage'
end
